.github/CONTRIBUTING.md
closes #3 
Added contributing.md which shows contribution guidelines including PR, code conventions, and other relevant information for first-time contributors to read
No notes
=> Added contributing.md

backend/README.md
Refers to #1 
Added readme.md which shows how to set up and run the backend. Demonstrates how to add new endpoints and where files should be located.
As I am only familiar with the backend, this does not include a readme for frontend or testing.
=> Add backend readme

frontend/package-lock.json, frontend/package.json, frontend/src/booking/ConfirmationContainer.js, frontend/src/booking/TimeContainer.js, frontend/src/index.js, frontend/src/store/booking/bookingActions.js, frontend/src/store/booking/bookingReducer.js, frontend/src/store/rootReducer.js, frontend/src/store/store.js
Closes #35 
Used Redux for state management between components
Set up a basic example using the number of seats 
=> Adding state management

backend/.eslintrc.json, backend/.prettierrc, backend/app.js, backend/config/config.js, backend/database.js, backend/package-lock.json, backend/package.json, backend/routes/reservation.js, backend/routes/restaurant.js, backend/sqlConnectionResolver.js, backend/tests/mockSQL.js, backend/tests/reservation/deleteSingle.js, backend/tests/reservation/getAll.js, backend/tests/reservation/getSingle.js, backend/tests/reservation/postSingle.js
closes #23 closes #19 closes #22 
Setup reservation endpoint for:
- a user to retrieve their reservation, using their reservationID
- a restaurant manager to get all reservations for their restaurant, using their restaurantID
- a user to add a new reservation. Returning a new reservationID
- a user to cancel a booking, using their reservationID
Setup a basic mock test suite.
Due to the inability to flush a shared database between tests and the setup required to clone and set up a local database, a mock SQL connection was created. This allows tests to check that the correct SQL query was created.
Due to tests not reaching a real database, many scenarios will not be able to be tested (eg foreign key constraints).
=> Add reservation endpoint. Setup mock tests

backend/README.md
closes #51 
Updated the backend readme to explain how to set up and run the tests.
Added a section for solutions to common build/run issues.
No other notes
=> Update backend readme for test setup

frontend/package-lock.json, frontend/package.json, frontend/src/booking/BookingPage.module.css, frontend/src/booking/TimeContainer.js, frontend/src/general/textHolder.js, frontend/src/store/booking/bookingActions.js, frontend/src/store/booking/bookingReducer.js
closes #41 
Set up the booking details page where a user can enter their desired time, date and number of guests. The date and number of guests are set up completely and are save in the redux store. The time is not yet implemented and will be done so by @mmir415 when the TimeContainer is implemented. These changes use the material ui pickers and date io packages.
I am not completely sure how we wanted to save the booking state, so I just made it all done in one methods I am open to suggestions on how better ways to do it because I am pretty unversed in redux. I also haven't added any error checking for the selected date and number of seats, i.e. ensuring the date hasn't already passed. I thought it would be better to work on sanity checking after more important functionality is complete.
=> Add page to enter booking details and save these details in state

frontend/src/landing/LandingPage.js
[Github supports linking PR's to issues to auto close them!]
closes #72
Removed default import error on the landingpage searchbar
closes #72
=> fixed default import error on searchbar

frontend/.eslintrc.js, frontend/src/booking/BookingPage.module.css, frontend/src/booking/DetailsContainer.js
closes #49 
Basic interface for users to enter their booking details
=> User Interface for Booking Details #49

backend/routes/restaurant.js, backend/tests/restaurant/getall.js, backend/tests/restaurant/openhours.js, package-lock.json
Closes #18 
Added endpoint for listing all the restaurants, and getting the opening hours for restaurant. Unit tests not included. From my understanding, the testing team will implement this? closes #18 
=> Add endpoints for getting all restaurants, and opening hours. #18

testing/cypress/integration/restaurant_routing.spec.js
Fixed IP visited to be more generalized, changed css selector, removed unused code
Corrected git workflow in this PR
=> Restaurant navigation tests unable to pass for different testers

backend/app.js, backend/routes/user.js, backend/tests/user/testCreateUser.js, backend/tests/user/testUpdateUser.js
closes #24 
Added endpoints for creating and updating user + tests for both.
None
=> Add endpoints for creating and updating a user

backend/config/config.js, backend/routes/reservation.js, backend/tests/reservation/update.js
closes #21 
This endpoint allows user to update their booking after it is made. They can edit:
- Name
- Phone Number
- Email
- Date
- Time
- Number of Guests
- Notes
It will also check if the change is being made more than an hour prior to the reservation, otherwise changes are not permitted. A common function was created to test this condition, so the DELETE /single endpoint has been changed to use this function 
Two very basic error handling unit tests have been created, but due to tests not reaching a real database, many scenarios will not be able to be tested in the current state.
=> Add update reservation endpoint

frontend/src/booking/ConfirmationContainer.js, frontend/src/booking/DetailsContainer.js, frontend/src/booking/TimeContainer.js, frontend/src/general/textHolder.js, frontend/src/store/booking/bookingActions.js, frontend/src/store/booking/bookingReducer.js
closes #70 and #83 
Sets up the booking confirmation page to allow the user to view the booking details before they accept it. Additionally, this PR fixes issues with redux and state management and got it working with with the three pages, TimeContainer, DetailsContainer and ConfirmationContainer
For the booking confirmation page you need a modal to open on click confirmation to show the user their booking ID or return an error if it fails. This will be implemented later
=> Add booking confirmation page and complete redux state management functionality

backend/routes/restaurant.js
Closes  #48 
Changed the database to auto-increment ID, and changed the endpoint to reflect.
=> Change add restaurant to use auto-increment

frontend/src/App.js, frontend/src/booking/DetailsContainer.js, frontend/src/landing/LandingPage.js, frontend/src/landing/LandingPage.module.css, frontend/src/restaurant/RestaurantViewBookingPage.js
Closes #112
Added a button which routes to the view bookings screen
=> Added route for restaurants view

backend/routes/reservation.js, backend/routes/restaurant.js
closes #109
GET reservation/single?reservationID=x => GET reservation/single/x
DELETE reservation/single?reservationID=x => DELETE reservation/x
GET reservation/all => get reservation/
POST reservation/single => POST reservation/
GET restaurant?restaurantID=x => GET restaurant/x
GET restaurant/openhours?restaurantID=x =>GET restaurant/x/openhours
GET restaurant/getall => GET restaurant/
DELETE restaurant?restaurantID=x => DELETE restaurant/x
Changed any swagger docs to include in-path params.
I have not developed tests for this api and the test suite will be broken upon merging this branch. This is intended and up to @itsercleung @nidhineshnand to discuss in a further meeting.
=> Change api syntax

frontend/package-lock.json, frontend/package.json, frontend/src/general/config.js, frontend/src/landing/NoRestaurants.js, frontend/src/landing/RestaurantTile.js, frontend/src/store/restaurant/restaurantAction.js, frontend/src/store/restaurant/restaurantEpic.js, frontend/src/store/restaurant/restaurantReducer.js, frontend/src/store/rootEpic.js, frontend/src/store/rootReducer.js, frontend/src/store/store.js
Closes #105 
Get all restaurants from back-end API
Set up epics
Only works with back-end is running, otherwise it shows that nothing is there
=> Show restaurants with API data

backend/routes/user.js, backend/swagger.js
closes #106 
Added swagger docs in backend/routes/user.js
None
=> Swagger docs for create and update user endpoints

frontend/.eslintrc.js, frontend/package-lock.json, frontend/package.json, frontend/src/booking/BookingPage.js, frontend/src/booking/BookingPage.module.css, frontend/src/booking/ConfirmationContainer.js, frontend/src/booking/ConfirmationContainer.module.css, frontend/src/booking/ConfirmedBooking.js, frontend/src/booking/ContentContainer.js, frontend/src/booking/ContentContainer.module.css, frontend/src/booking/DetailsContainer.js, frontend/src/booking/DetailsContainer.module.css, frontend/src/general/textHolder.js, frontend/src/landing/LandingPage.js, frontend/src/landing/LandingPage.module.css, frontend/src/landing/edit/BookingEditPopupButton.js
Closes #115, closes #77
Update the UI to match the landing page
Added a progress, to indicate to the user what stage they're at for the booking
=> Booking confirmation and detail page design revamp

backend/routes/reservation.js, backend/tests/reservation/getAvailable.js
Closes #92 
Add a call to get all available tables for a restaurant.
Added unit test for feature
=> Add an endpoint that gets available tables for reservation

backend/routes/reservation.js
Closes #126 
Update swagger documents to allow strings for reservation id.
=> Fixed reservation id parameter in swagger

.github/pull_request_template.md
closes #118 
A few sentences describing the overall goals of the pull request's commits.
=> fixed typos on pr template

backend/routes/user.js
closes #131 
- Adds a get endpoint that allows the user object to be fetched by using a user ID
- Adds swagger docs for the get request
=> Added get api endpoint for user and swagger docs

backend/routes/reservation.js
closes #130 
Swagger docs now show GET reservation/
=> changed restaurantID from in path to in query on reservation swagger docs

frontend/src/restaurant/RestaurantViewBookingPage.js, frontend/src/restaurant/RestaurantViewBookingPage.module.css
closes #114
Added mock screen for viewing all available bookings for a single restaurant
N/A
=> Updated restaurant view booking page w some style

frontend/src/App.js, frontend/src/booking/BookingPage.js, frontend/src/booking/BookingPage.module.css, frontend/src/booking/ConfirmationContainer.js, frontend/src/booking/ConfirmedBooking.js, frontend/src/booking/ConfirmedBooking.module.css, frontend/src/booking/TimeContainer.js, frontend/src/general/config.js, frontend/src/general/textHolder.js, frontend/src/landing/LandingPage.js, frontend/src/landing/RestaurantTile.js, frontend/src/landing/edit/BookingEditPopup.module.css, frontend/src/landing/edit/BookingEditPopupDialog.js, frontend/src/landing/edit/getRestaurantByID.js, frontend/src/landing/edit/getRestaurantByReference.js, frontend/src/landing/edit/getUserById.js, frontend/src/restaurant/RestaurantViewBookingPage.js, frontend/src/store/booking/bookingActions.js, frontend/src/store/booking/bookingEpic.js, frontend/src/store/booking/bookingReducer.js, frontend/src/store/restaurant/restaurantAction.js, frontend/src/store/restaurant/restaurantEpic.js, frontend/src/store/restaurant/restaurantReducer.js, frontend/src/store/rootEpic.js, frontend/src/store/rootReducer.js
Closes #123 
Fetch calls to receive data from the backend
Display the data in the correct format
Allow enabling/disabling of time buttons
Note: some post/put requests are hard coded for demonstration purposes
=> API integration with backend

testing/cypress/integration/homepage_function.spec.js
=> Add testcase for homepage.

.github/workflows/Backend_CI.yml, backend/database.js, backend/tests/setup.js, backend/tests/tests.js
closes #156 
Setup GitHub action CI pipeline to run on all backend PR's and commits to master. Will run all tests.
=> Setup Backend CI Pipeline

frontend/src/landing/LandingPage.module.css, frontend/src/landing/RestaurantTile.js
Closes #180 
This PR adds a dummy button to restaurant card components which is consistent with styling provided in the hi-fi prototype. This does not yet have any functionality as this is to be implemented in a later ticket.
=> Add Menu Button to Restaurant Cards

backend/restaurant_db.sql
Closes #210 
- REVIEW table has been created in the database
- Updated the .sql dump file to include the REVIEW table
=> updated dump file with new table REVIEW

backend/restaurant_db.sql
Closes #239 
- Added Name, Phone and Email columns to the Reservation table in the database
- Updated the dump file
=> updated reservation table with customer details

backend/restaurant_db.sql
Closes #183 
- Created new table MENU in the database to store menus for restaurant
- Updated restaurant_db.sql dump file with the MENU table
=> updated dump file with menu table, cleaned all dummy data

frontend/src/booking/TimeContainer.js, frontend/src/general/helperFunctions.js
#178
I have fixed a bug where the user can select the time that is past from the present time. 
=> Feature/disable the past date/time in booking #178

backend/restaurant_db.sql
Closes #260 
Auto-increments IDs for Review and Menu tables 
=> updated Review and Menu tables; auto-increment IDs

backend/restaurant_db.sql, backend/routes/restaurant.js
Closes #169 
Added column for image url in the database restaurant table. Added optional image url input to the create restaurant post endpoint.
As the endpoints to get restaurant data all return "*" then they do not have to be updated to include the newly updated column in the restaurant table
=> Add custom image support for restaurants in backend

frontend/src/restaurant/RestaurantViewBookingPage.js, frontend/src/store/booking/bookingEpic.js, frontend/src/store/booking/bookingReducer.js
Closes #213 
The delete and modify reservations buttons did not do anything when clicked.
The corresponding actions now occur when these buttons are clicked
- Clicking on 'delete' deletes a booking from the database 
- Clicking on 'modify' takes you to the edit booking page
=> Fixed delete/modify on reservations page

frontend/src/landing/RestaurantTile.js
Fixes #262 
Needed to move pop up component outside of parent so it doesn't trigger its onClick handler
(All frontend tests fail, I think they need updating)
=> Fixed popup menu being clickable

frontend/src/booking/TimeContainer.js
#272 
Available booking times now update as the number of guests gets typed in.
=> Fixed booking times not updating

backend/restaurant_db.sql, backend/routes/restaurant.js
Closes #276
Created endpoint to get new restaurants (restaurants created in the last month). The endpoint utilises an offset and a limit. Added DateAdded column to the restaurant table in the database.
=> Create get new restuarants endpoint

frontend/src/booking/BookingPage.js
Closes #246 
Adds popup when trying to exit out of booking process to confirm with user that they want to leave.
=> Prompt for leaving booking process

frontend/package-lock.json, frontend/src/landing/LandingPage.module.css, frontend/src/landing/menu/MenuPopupButton.js
Closed #300 
Adds a button on the top right corner of the menu popup. This button leads user to the restaurant's website. Currently, it's a dummy link.
Looks like this:
=> Adds button to restaurant's website on menu popup
